### ISSUE TITLE
Rendering the development spec

### ISSUE THREAD

**Issue by Tieske** [homieiot/homieiot.github.io#16]
The current development spec is rendered in a weird way. The "Topology" heading is somehow moved to the very. end of the rendered page. Which is not where it lives in the source doc.

**Comment by Thalhammer** [comment]
OK so I think I figured out whats happening. It looks like the way the grabrepo script works is it pulls all headings that are not mentioned in `keepsections` inside `multiversion.yml` from the latest develop version and not the version it was when the tag was done and then appends the `keepsection` sections at the end using the content of the tag. IMHO this is a very way of building the spec because it can cause the website version of the spec and the repo version at the given tag to heavily deviate. I have no idea why this extra step was implemented in the first place.

**Comment by Thalhammer** [comment]
Should be fixed by #18

**Comment by Thalhammer** [comment]
The ToC never worked for me, it threw all kinds of js errors in console, so I removed it. If its still needed I can take a look and rework it.

**Comment by Thalhammer** [comment]
Though I think instead of bringing back the JS table of contents it might make more sense to use the [hugo builtin](https://gohugo.io/methods/page/tableofcontents/) and have it statically generated.

**Comment by Tieske** [comment]
I think that for navigating the spec we need some sort of ToC.

Unfortunately I have 0 skills on the techstack used here 😞

**Comment by Thalhammer** [comment]
> Unfortunately I have 0 skills on the techstack used here

Yeah I don't really either, but I'll check if I can bring something up.

**Comment by Thalhammer** [comment]
TOC should be back with #26

**Comment by Tieske** [comment]
Nice!
